import { useRef } from "react";
import { AlertTriangle, Ban, Scale, FileWarning, Gavel } from "lucide-react";
import { useIntersection } from "@/hooks/use-intersection";
import { cn } from "@/lib/utils";

const risks = [
  {
    icon: AlertTriangle,
    title: "AI Hallucinations",
    description: "False information generated by AI systems in client deliverables",
  },
  {
    icon: Scale,
    title: "Algorithmic Bias & Discrimination",
    description: "Unfair outcomes from AI-driven decisions affecting protected classes",
  },
  {
    icon: Ban,
    title: "AI-Generated IP Infringement",
    description: "Copyright and intellectual property violations from AI outputs",
  },
  {
    icon: FileWarning,
    title: "Professional Negligence",
    description: "Liability from AI-assisted work that fails professional standards",
  },
];

const ProblemSection = () => {
  const ref = useRef<HTMLElement>(null);
  const isVisible = useIntersection(ref);
  return (
    <section ref={ref} className={cn("section-padding gradient-cream", "fade-in-section", isVisible && "is-visible")}>
      <div className="container-narrow">
        {/* Section Header */}
        <div className="text-left mb-16">
          <h2 className="text-xl sm:text-2xl md:text-3xl lg:text-4xl font-serif font-bold text-foreground mb-4 leading-tight">
            The Gap Isn&apos;t in the AI. It&apos;s in the Oversight.
          </h2>
          <p className="text-muted-foreground text-lg">
            When an employee submits an AI-generated deliverable without verifying its accuracy, that is a professional negligence event. Berkley&apos;s absolute AI exclusion bars coverage for it. Hamilton&apos;s generative AI exclusion bars coverage for it. Your broker may not have told you yet.
          </p>
        </div>

        {/* Risk Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-12">
          {risks.map((risk, index) => (
            <div 
              key={index}
              className="card-enterprise group hover:border-teal-dark/30 transition-all duration-300"
            >
              <div className="flex items-center gap-3 mb-4">
                <div className="w-12 h-12 rounded-lg bg-navy-deep/10 flex items-center justify-center flex-shrink-0 group-hover:bg-teal-dark/10 transition-colors">
                  <risk.icon className="w-6 h-6 text-navy-deep" />
                </div>
                <h3 className="text-sm font-semibold text-foreground leading-tight">{risk.title}</h3>
              </div>
              <p className="text-muted-foreground text-sm">{risk.description}</p>
            </div>
          ))}
        </div>

        {/* Stat Callout */}
        <div className="stat-callout text-center">
          <p className="text-4xl md:text-5xl font-serif font-bold text-cream mb-3">87%</p>
          <p className="text-cream/90 text-lg max-w-xl mx-auto">
            of enterprises currently utilize artificial intelligence in their operations. However, standard insurance policies typically exclude coverage for AI-related liabilities, creating a significant protection gap.
          </p>
        </div>
      </div>
    </section>
  );
};

export default ProblemSection;
